### ISSUE TITLE
Hiding a tab in Mobile view but not Desktop

### ISSUE THREAD

**Issue by xann1891** [jellekralt/Responsive-Tabs#129]
I want to be able to have a tab and its contents visible in the tab/desktop view, but hidden in the mobile/accordion view.  I have tried adding a class="hidden" to the <li> and <div> and then setting that class to display:none for tablet & mobile views; however, it is still showing up when I look at it in tablet/mobile view.

Any help would be appreciated!

**Comment by jellekralt** [comment]
Adding a class would not work indeed, because the tab elements for the accordion view are generated, and don't copy classes from the original element. You could solve this by using the `activateState` callback, or (if you only need to hide it for accordion) just remove the accordion element on load.

**Comment by xann1891** [comment]
I think that removing the accordion element on load would be best.  What code would I need to add to make that happen?

**Comment by jellekralt** [comment]
You'll have to write a bit of code that selects the accordion titles, maybe based on the `r-tabs-accordion-title` class. You'll have to come up with the code yourself :). 

Because this issue relates to your specific project, I'll close it for now
