### ISSUE TITLE
Loading other tabs, causes Slick carousel not to show unless page loads on active tab

### ISSUE THREAD

**Issue by leecollings** [jellekralt/Responsive-Tabs#52]
I'm having trouble understanding how to use your events to fire other elements. I have this code: 

    // hook into ResponsiveTabs event and manually trigger 'resize' event so that Slick recalculates the widths
    $('#horizontalTab').on('tab-load', function (e) {
        $('.slick-carousel-responsive').resize();
    });

However, I have no idea how to use the 'tab-load' events you've posted on your site. Can you please explain this, and hopefully give me a little push on how to set this resize() action up when the tabs load?

**Comment by leecollings** [comment]
Hi, sorry but I should update you. I believe I've managed to get it working now. It took me a moment to realise, the callbacks have to go into your code initialisation code like this:

    $('#horizontalTab').responsiveTabs({
        rotate: false,
        startCollapsed: 'accordion',
        collapsible: 'accordion',
        setHash: true,
        activate: function(){
            $('.slick-carousel-responsive').resize();
        }
    });

Which now has it working as I want. Just a tip, maybe you should include examples for the callbacks, as for me they're weren't as clear as the options to include them in this manner.

**Comment by leecollings** [comment]
Hmm actually it seems to be a bit sporadic. On some page loads, the callback doesn't seem to be called everytime.

So I switched to load, as I believe this is closer to what I want, but in this case the resize function never happens at all.

Is there anything you would suggest?

**Comment by jellekralt** [comment]
Hi there,
Sorry for the late response. Could you specify in which situation the callback doesn't get called? The activate callback is used in the demo, and AFAIK this works correctly: http://jellekralt.github.io/Responsive-Tabs/demo/demo.html

You should definitely use the activate callback for this. Like you've correctly discovered this problem lies with the slick plugin itself, or rather the fact that css doesn't get rendered correctly when initialized in a ```display: none``` element (this also happens with plugins like jQuery UI tabs). The only way to fix this is a re-render of the plugin when the tab panel opens (which is where the activate function comes in :).

Let me know if you can find an example of a scenario where the callback doesn't get called!

**Comment by jellekralt** [comment]
Closing this for now

**Comment by neilgee** [comment]
```
jQuery(document).ready(function($){

    $('#include-tabs').responsiveTabs({
	   startCollapsed: 'accordion',
	   setHash: true,
	   // Add other parameters
	    activate: function(){
			$('.slick-slider').slick('refresh'); // Refresh on Activated Tab
		}
	});
	
});
```
