### ISSUE TITLE
Conflict with jquery bxSlider

### ISSUE THREAD

**Issue by banifou** [jellekralt/Responsive-Tabs#69]
I'm using an image slider from jquery (bxslider) in a secondary tab. The slider doesn't work properly. Sometimes the are there after clicking the tab, sometimes not! After switching btw. the tabs, the images in the slider are gone, or only small images like thumbnails are shown.
Any help to fix this? Thanks

**Comment by jellekralt** [comment]
This problem is not caused by this plugin, but is a problem with a lot of plugins in general. Basically, this problem occurs because the bxslider plugin is initialized in an html element which is hidden with ```display: none```. For more info, check out: http://stackoverflow.com/questions/11071269/bxslider-within-show-hide-divs
